name: Gixa
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  get: ^4.7.3
  lottie: ^3.3.2
  smooth_page_indicator: ^1.1.0
  eva_icons_flutter: ^3.1.0
  http: ^1.2.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  device_info_plus: ^10.1.0
  firebase_auth: ^6.1.4
  # firebase_messaging: ^15.1.0
  # firebase_core: ^3.8.0
  flutter_secure_storage: ^9.2.2
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  url_launcher: ^6.2.0
  file_selector: ^1.0.3
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  razorpay_flutter: ^1.4.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_pdfview: ^1.3.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  firebase_messaging: ^16.1.1
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.10








dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21
  remove_alpha_ios: true



flutter:
  
  uses-material-design: true

  assets:
    - assets/lottie/otp.json
    - assets/lottie/verify_otp.json
    - assets/lottie/error.json
    - assets/lottie/AiData.json
    - assets/lottie/Search_Doctor.json
    - assets/lottie/OnlineLearning.json
    - assets/lottie/premium.json
    - assets/images/doctors.svg



    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
